#!/usr/bin/env python3
"""Pulls the brushed MR/SC letters out of Branding/wordmark/wordmark.svg for the website.
Run again after the logo changes: python3 website/tools/build_assets.py"""
import json, os, re

here = os.path.dirname(os.path.abspath(__file__))
site = os.path.join(here, "..")
svg = open(os.path.join(here, "../../Branding/wordmark/wordmark.svg")).read()
letters = re.findall(r'<path d="([^"]+)"', svg)
assert len(letters) == 4, f"expected 4 letters, found {len(letters)}"

open(os.path.join(site, "assets/wordmark.js"), "w").write(
    "// Generated by website/tools/build_assets.py from Branding/wordmark/wordmark.svg. Do not edit.\n"
    "window.MRSC_LETTERS = " + json.dumps(letters) + ";\n")

paths = "".join(f'<path d="{d}"/>' for d in letters)
def icon(bg, rx):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">'
            f'<rect width="1024" height="1024" rx="{rx}" fill="{bg}"/><g fill="#fff">{paths}</g></svg>\n')
open(os.path.join(site, "assets/icon.svg"), "w").write(icon("#FF3B5C", 0))
open(os.path.join(site, "assets/favicon.svg"), "w").write(icon("#FF3B5C", 230))
print("ok")
