#!/usr/bin/env python3
"""Single source for the MRSC hand-lettered wordmark.
Generates: ../../MRSC/WordmarkData.swift, ../../MRSC/AppIcon*.icon bundles, wordmark.svg preview."""
import json, os, shutil

# Letters in a 100x100 box, drawn as the pen moves (M/L/C only). Wobble is baked in on purpose.
LETTERS = {
    "M": ("M4 98 L9 4 L50 62 L91 2 L97 97", 100),
    "R": ("M8 98 L6 3 C40 -2 88 2 86 30 C84 56 46 58 10 52 M38 55 L90 99", 92),
    "S": ("M88 14 C66 -6 12 -2 14 28 C16 54 86 44 86 72 C86 104 30 104 8 84", 96),
    "C": ("M90 16 C62 -8 2 -2 4 50 C6 102 66 108 92 82", 96),
}
GAP = 30
UNDERLINE = "M4 134 C130 118 320 144 470 124"

COLORS = {  # id: (name, background hex)
    "red": ("Red", "#FF3B5C"), "orange": ("Orange", "#FF7A1A"), "green": ("Green", "#18B56A"),
    "blue": ("Blue", "#2F6BFF"), "violet": ("Violet", "#7C4DFF"), "black": ("OLED", "#000000"),
}

import math, random, re

def flatten(d, step=4.0):
    """Centerline of an M/L/C path as dense points (letter units)."""
    t = re.findall(r'[MLC]|-?\d+\.?\d*', d); i = 0; cur = None; strokes = []; pts = []
    def num(): 
        nonlocal i; v = float(t[i]); i += 1; return v
    while i < len(t):
        c = t[i]; i += 1
        if c == "M":
            if pts: strokes.append(pts)
            cur = (num(), num()); pts = [cur]
        elif c == "L":
            n = (num(), num()); L = math.dist(cur, n); k = max(1, int(L / step))
            pts += [(cur[0] + (n[0] - cur[0]) * j / k, cur[1] + (n[1] - cur[1]) * j / k) for j in range(1, k + 1)]; cur = n
        elif c == "C":
            a = (num(), num()); b = (num(), num()); e = (num(), num()); k = 40
            for j in range(1, k + 1):
                u = j / k; m = 1 - u
                pts.append((m**3*cur[0] + 3*m*m*u*a[0] + 3*m*u*u*b[0] + u**3*e[0], m**3*cur[1] + 3*m*m*u*a[1] + 3*m*u*u*b[1] + u**3*e[1]))
            cur = e
    if pts: strokes.append(pts)
    # resample evenly
    out = []
    for p in strokes:
        res = [p[0]]; acc = 0.0
        for a, b in zip(p, p[1:]):
            seg = math.dist(a, b)
            while acc + seg >= step:
                f = (step - acc) / seg; a = (a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f)
                res.append(a); seg = math.dist(a, b); acc = 0.0
            acc += seg
        res.append(p[-1]); out.append(res)
    return out

CELL = 3.0; OX = [196, 530]; OY = [226, 562]

def brush(idx, key, rng):
    """Dry-brush letter as a union of rough dabs. Returns one 'M..L..Z' string in 1024 space."""
    d, w = LETTERS[key]
    x0 = OX[idx % 2] + (300 - w * CELL) / 2; y0 = OY[idx // 2]
    rot = rng.uniform(-0.05, 0.05); cs, sn = math.cos(rot), math.sin(rot)
    ph = [rng.uniform(0, 6.28) for _ in range(4)]
    parts = []
    for stroke in flatten(d):
        n = len(stroke)
        for j, (px, py) in enumerate(stroke):
            u = j / max(1, n - 1)
            x = (px - w / 2) * CELL; y = (py - 50) * CELL
            x, y = x * cs - y * sn + w / 2 * CELL, x * sn + y * cs + 50 * CELL
            x += x0 + 3.5 * math.sin(u * 9 + ph[0]); y += y0 + 3.5 * math.sin(u * 7 + ph[1])
            press = 1.0 + 0.16 * math.sin(u * 13 + ph[2]) + 0.1 * math.sin(u * 31 + ph[3])
            taper = 0.55 + 0.45 * min(1, u * 6, (1 - u) * 3.5) if n > 6 else 1
            r = 34 * press * taper
            m = 11; pts = []
            for k in range(m):
                a = 2 * math.pi * k / m
                rr = r * (1 + rng.uniform(-0.1, 0.1))
                pts.append((x + rr * math.cos(a), y + rr * math.sin(a)))
            parts.append("M" + " L".join(f"{a:.0f} {b:.0f}" for a, b in pts) + " Z")
    return " ".join(parts)

def paths():
    rng = random.Random(11)
    return [brush(i, k, rng) for i, k in enumerate(LETTERS)]

def swift():
    s = "// Generated by Branding/wordmark/build.py. Do not edit.\nenum WordmarkData {\n"
    s += "    nonisolated static let size: Double = 1024\n"
    s += "    nonisolated static let letters: [String] = [\n" + "".join(f'        "{d}",\n' for d in paths()) + "    ]\n}\n"
    return s

def icon_layer():
    g = "".join(f'<path d="{d}"/>\n' for d in paths())
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">\n'
            '<g fill="#fff">\n' + g + '</g></svg>\n')

def rgb(h): return ",".join(f"{int(h[i:i+2],16)/255:.5f}" for i in (1, 3, 5))

def icons(root):
    for cid, (_, hexv) in COLORS.items():
        name = "AppIcon" if cid == "red" else "AppIcon-" + cid.capitalize()
        p = os.path.join(root, name + ".icon"); shutil.rmtree(p, ignore_errors=True)
        os.makedirs(p + "/Assets")
        open(p + "/Assets/wordmark.svg", "w").write(icon_layer())
        json.dump({"fill": {"solid": f"srgb:{rgb(hexv)},1.00000"},
                   "groups": [{"layers": [{"image-name": "wordmark.svg", "name": "MRSC"}],
                               "shadow": {"kind": "neutral", "opacity": 0.35},
                               "translucency": {"enabled": False, "value": 0}, "specular": True}],
                   "supported-platforms": {"circles": ["watchOS"], "squares": "shared"}},
                  open(p + "/icon.json", "w"), indent=2)

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__)); app = os.path.join(here, "../../MRSC")
    open(os.path.join(app, "WordmarkData.swift"), "w").write(swift())
    icons(app)
    open(os.path.join(here, "wordmark.svg"), "w").write(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><rect width="1024" height="1024" fill="#FF3B5C"/>' +
        icon_layer().split("\n", 1)[1])
    print("ok")
